# Generated by Django 3.1 on 2023-12-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20231221_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=450, unique=True)),
                ('slug', models.SlugField(max_length=450, unique=True)),
                ('short_description', models.TextField(max_length=800, unique=True)),
                ('product_description', models.TextField(blank=True, max_length=1500)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/product')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
